---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/12/2025 10:59 PM
---

data:extend({
    {
        type = "tips-and-tricks-item-category",
        name = "erm-unit-control",
        order = "n00-[ermuc-unit-control]-1"
    },
    {
        type = "tips-and-tricks-item",
        name = "ermuc-unit-control",
        --tag = "[entity=]",
        category = "erm-unit-control",
        order = "l1",
        starting_status = "suggested",
        is_title = true,
    },
    {
        type = "tips-and-tricks-item",
        name = "ermuc-control-listing",
        --tag = "[entity=]",
        category = "erm-unit-control",
        order = "l2",
        indent = 1,
        starting_status = "suggested",
    }
})